name: NuGetForUnity Restore
description: Install NuGetForUnity.Cli and restore NuGet packages for Unity

inputs:
  working-directory:
    description: Path to the Unity project root
    required: false
    default: .

runs:
  using: composite
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - run: dotnet tool install --global NuGetForUnity.Cli
      shell: bash

    - run: nugetforunity restore
      working-directory: ${{ inputs.working-directory }}
      shell: bash
